<a href="https://colab.research.google.com/github/guilhermeaugusto9/sigmoidal/blob/master/05_3_Lidando_com_vari%C3%A1veis_categ%C3%B3ricas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img alt="Colaboratory logo" width="15%" src="https://raw.githubusercontent.com/carlosfab/escola-data-science/master/img/novo_logo_bg_claro.png">

#### **Data Science na Prática 2.0**
*by [sigmoidal.ai](https://sigmoidal.ai)*

---

# Lidando com variáveis categóricas

Em machine learning, muitos modelos não conseguirão lidar diretamente com variáveis categóricas. Dessa maneira, é importante conhecer os principais métodos e saber como aplicá-los.

Nesta aula veremos como usar o `LabelEncoder` e `OneHotEncoder`. Mais que isso, vou te mostrar algumas situações onde colunas numéricas são, na verdade, variáveis categóricas.

Para exemplificar o uso dessas técnicas, vou usar o dataset de câncer de mama, disponibilizado pela [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/breast+cancer).

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/breast-cancer.data", header=None,
                 names=["class", "age", "menopause", "tumor_size",
                        "inv_nodes", "nodes-caps", "deg_malig", "breast",
                        "breast_quad", "irradiat"])

df.head()

class    age menopause  ... breast breast_quad irradiat
0  no-recurrence-events  30-39   premeno  ...   left    left_low       no
1  no-recurrence-events  40-49   premeno  ...  right    right_up       no
2  no-recurrence-events  40-49   premeno  ...   left    left_low       no
3  no-recurrence-events  60-69      ge40  ...  right     left_up       no
4  no-recurrence-events  40-49   premeno  ...  right   right_low       no

[5 rows x 10 columns]

In [ ]:
X = df.drop('class', axis=1)
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y)

## Label encoding

In [ ]:
# y_train antes do encoding
y_train

118    no-recurrence-events
8      no-recurrence-events
231       recurrence-events
112    no-recurrence-events
165    no-recurrence-events
               ...         
166    no-recurrence-events
213       recurrence-events
156    no-recurrence-events
248       recurrence-events
262       recurrence-events
Name: class, Length: 214, dtype: object

In [ ]:
# y_test antes do encoding
y_test

140    no-recurrence-events
206       recurrence-events
80     no-recurrence-events
264       recurrence-events
247       recurrence-events
               ...         
25     no-recurrence-events
70     no-recurrence-events
134    no-recurrence-events
131    no-recurrence-events
10     no-recurrence-events
Name: class, Length: 72, dtype: object

In [ ]:
# codificando a variável alvo
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
# y_train depois do encoding
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1])

In [ ]:
# y_test depois do encoding
y_test

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0])

In [ ]:
# visualizando as classes (fase do fit)
le.classes_

array(['no-recurrence-events', 'recurrence-events'], dtype=object)

In [ ]:
# recuperando e convertendo os labels
le.inverse_transform(y_train)[:5]

array(['no-recurrence-events', 'no-recurrence-events',
       'recurrence-events', 'no-recurrence-events',
       'no-recurrence-events'], dtype=object)

## One-hot encoding

E quando a ordem não representa, necessariamente, uma escala real de importância?

<center><img alt="Colaboratory logo" width="45%" src="https://raw.githubusercontent.com/carlosfab/dsnp2/master/img/encoding.png"></center>


In [ ]:
# X_train antes do OneHotEncoder
X_train

age menopause tumor_size  ... breast breast_quad  irradiat
118  30-39   premeno      10-14  ...  right    left_low        no
8    40-49   premeno      50-54  ...   left    left_low        no
231  40-49   premeno      30-34  ...  right     left_up        no
112  40-49   premeno      20-24  ...  right     left_up        no
165  40-49   premeno      20-24  ...  right     left_up        no
..     ...       ...        ...  ...    ...         ...       ...
166  40-49   premeno      20-24  ...  right    left_low        no
213  50-59   premeno      25-29  ...  right     left_up        no
156  50-59      ge40      25-29  ...  right     left_up        no
248  60-69      ge40      35-39  ...   left    left_low        no
262  60-69      ge40      25-29  ...   left     left_up        no

[214 rows x 9 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

le = OneHotEncoder()
le.fit(X_train)
X_train_enc = le.transform(X_train)

In [ ]:
X_train_enc

<214x41 sparse matrix of type '<class 'numpy.float64'>'
	with 1926 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_enc.toarray()

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

## Dummies values

In [ ]:
pd.get_dummies(df, columns=['menopause', 'breast'])

class    age  ... breast_left breast_right
0    no-recurrence-events  30-39  ...           1            0
1    no-recurrence-events  40-49  ...           0            1
2    no-recurrence-events  40-49  ...           1            0
3    no-recurrence-events  60-69  ...           0            1
4    no-recurrence-events  40-49  ...           0            1
..                    ...    ...  ...         ...          ...
281     recurrence-events  30-39  ...           1            0
282     recurrence-events  30-39  ...           1            0
283     recurrence-events  60-69  ...           0            1
284     recurrence-events  40-49  ...           1            0
285     recurrence-events  50-59  ...           1            0

[286 rows x 13 columns]

In [ ]:
pd.get_dummies(df)

deg_malig  class_no-recurrence-events  ...  irradiat_no  irradiat_yes
0            3                           1  ...            1             0
1            2                           1  ...            1             0
2            2                           1  ...            1             0
3            2                           1  ...            1             0
4            2                           1  ...            1             0
..         ...                         ...  ...          ...           ...
281          2                           0  ...            1             0
282          3                           0  ...            0             1
283          1                           0  ...            1             0
284          3                           0  ...            1             0
285          3                           0  ...            1             0

[286 rows x 43 columns]

In [ ]:
df_enc = pd.get_dummies(df)